### ISSUE TITLE
BUG - Jarvis unresponsive on initial load #1

### ISSUE THREAD

**Issue by yilenpan** [UncomfortableEggnog/Jarvis#15]
On clean systems without electron installed, Jarvis becomes unresponsive. However, on reload, Jarvis becomes responsive.

**Comment by andresmm07** [comment]
I've been doing some testing to reproduce this error and get more info. It looks like this problem only happens when I open the app directly from the dmg. If I open the dmg > copy the content to a different folder > launch jarvis, the problem doesn't happen. I'm still testing to see if this is the actual problem, but if it is, I don;t think it is an issue with the app. We just have to add this to our documentation. this is the normal installation process of any app for mac. you usually don't launch the app when it is inside the dmg. 

please let me know if anyone can reproduce the issue when they move the app outside the dmg and what steps you  followed.

**Comment by andresmm07** [comment]
Ok, these are the steps to "resolve" the issue:

1) Download the DMG
2) Open the DMG
3) Drag and drop the Jarvis.app file to your Applications folder
4) Launch Jarvis from the Applications folder

The issue shouldn't happen if you do this. At least it doesn't happen to me. It only happens when I open the app from the dmg.

http://apple.stackexchange.com/questions/64845/how-do-i-install-applications-from-a-dmg-file

Please let me know if this doesn't resolve the problem for some of you.

**Comment by yilenpan** [comment]
Solved in 0.0.2, closing
